import { arraySidebar } from "vuepress-theme-hope";

export const qccstp = arraySidebar([
  "",
  {
    text: "软件设计师",
    prefix: "software-design-engineer/",
    collapsible: true,
    children: [
      "start",
      "computer-composition-and-structure",
      "program-language",
      "operating-system",
      "fundamentals-of-software-engineering",
      "system-development-and-operation",
      "basic-knowledge-of-network-and-multimedia",
      "database-technology",
      "algorithms-and-data-structures",
      "object-oriented-technology",
      "standardization-and-intellectual-property",
    ],
  },
  {
    text: "系统架构设计师",
    prefix: "system-architect/",
    collapsible: true,
    children: [
      "start",
      "enterprise-informatization-strategy-and-implementation",
      "software-engineering",
      "software-architecture-design",
      "design-thesis",
      "system-security-analysis-and-design",
      "system-reliability-analysis-and-design",
      "project-management",
      "computer-composition-and-architecture",
      "system-configuration-and-performance-evaluation",
      "case-analysis",
      "operating-system",
      "computer-network",
      "database-system",
      "intellectual-property-and-standardization",
      "mathematics-and-economic-management",
    ],
  },
]);
